[package]
name = "rust-effectserver"
version = "0.1.0"
authors = ["Tommi Teistelä <totateis@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
serialport = "3.2.0"
byteorder = "1.3.1"
