[package]
name = "effectserver2-rs"
version = "0.3.0"
authors = ["Tommi Teistelä <totateis@gmail.com>"]
edition = "2018"
license = "MIT"

default-run = "effectserver"

[dependencies]
byteorder = "1.3.1"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
serde_yaml = "0.8.8"
serialport = "3.2.0"
warp = "0.2.1"
tokio = "0.2.13"
futures = "0.3.4"
crossbeam = "0.7.3"
